### ISSUE TITLE
pip installation process doesn't work

### ISSUE THREAD

**Issue by Mark-E-Hamilton** [Exirel/pylint-json2html#1]
Hi,

I'm using python 2.7.4, and I tried to install this package using this command:

   pip install --target=/projects/sierra/linux_rh6/install/Python/extras.new/lib/python2.7/site-packages pylint-json2html
 Collecting pylint-json2html
   Using cached https://files.pythonhosted.org/packages/b0/07/94c291904fcdd8a5cb133dcf475489304d471a3e4d6fcd6d19582b8fbfb8/pylint-json2html-0.1.0.tar.gz
  Running setup.py (path:/tmp/pip-install-w0dur9/pylint-json2html/setup.py) egg_info for package pylint-json2html produced metadata for project name unknown. Fix your #egg=pylint-json2html fragments.
 Installing collected packages: unknown
   Running setup.py install for unknown ... done
 Successfully installed unknown-0.0.0

I got the output shown above, which seems incorrect, and no pylint-json2html was installed anywhere that I could find.
 $ find /projects/sierra/linux_rh6/install/Python/extras.new -name pylint-json2html
 $
 $ find /projects/sierra/linux_rh6/install/Python/extras.new -name '\*json2html\*'
 $
The site-packages directory contains this ,which also seems incorrect:
 $ ls .../lib/python2.7/site-packages
 UNKNOWN-0.0.0-py2.7.egg-info/

 FWIW, I also tried installing it from the pypi package, and got this result:
 [pylint-json2html-0.1.0]$ python setup.py install --prefix=${EXTRAS_PATH:?}
 running install
 running bdist_egg
 running egg_info
 writing UNKNOWN.egg-info/PKG-INFO
 writing top-level names to UNKNOWN.egg-info/top_level.txt
 writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
 reading manifest file 'UNKNOWN.egg-info/SOURCES.txt'
 reading manifest template 'MANIFEST.in'
 warning: no previously-included files matching '__pycache__' found under directory '*'
 warning: no previously-included files matching '*.py[co]' found under directory '*'
 warning: no previously-included files matching '*' found under directory 'tests'
 writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
 installing library code to build/bdist.linux-x86_64/egg
 running install_lib
 warning: install_lib: 'build/lib' does not exist -- no Python modules to install

 creating build/bdist.linux-x86_64/egg
 creating build/bdist.linux-x86_64/egg/EGG-INFO
 copying UNKNOWN.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
 copying UNKNOWN.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
 copying UNKNOWN.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
 copying UNKNOWN.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
 zip_safe flag not set; analyzing archive contents...
 creating 'dist/UNKNOWN-0.0.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
 removing 'build/bdist.linux-x86_64/egg' (and everything under it)
 Processing UNKNOWN-0.0.0-py2.7.egg
 Removing /projects/sierra/linux_rh6/install/Python/extras.new/lib/python2.7/site-packages/UNKNOWN-0.0.0-py2.7.egg
 Copying UNKNOWN-0.0.0-py2.7.egg to /projects/sierra/linux_rh6/install/Python/extras.new/lib/python2.7/site-packages
 UNKNOWN 0.0.0 is already the active version in easy-install.pth

 Installed /projects/sierra/linux_rh6/install/Python/extras.new/lib/python2.7/site-packages/UNKNOWN-0.0.0-py2.7.egg
 Processing dependencies for UNKNOWN==0.0.0
 Finished processing dependencies for UNKNOWN==0.0.0

**Comment by Exirel** [comment]
Hi @Mark-E-Hamilton,

Sorry for the inconvenience but there is no plan to support Python version prior to 3.4: Python 2.7 is not a supported version. Even if you could install it, I'm not sure it would work at all.

Of course you can still use an older version of `pylint` to keep an HTML report if you really need to.

**Comment by Mark-E-Hamilton** [comment]
Thanks. Sticking with an old version of pylint it probably what we'll do.

On 05/07/18 17:44, Florian Strzelecki wrote:
> Hi @Mark-E-Hamilton <https://github.com/Mark-E-Hamilton>,
>
> Sorry for the inconvenience but there is no plan to support Python
> version prior to 3.4: Python 2.7 is not a supported version. Even if you
> could install it, I'm not sure it would work at all.
>
> Of course you can still use an older version of |pylint| to keep an HTML
> report if you really need to.


-- 
----------------
Mark E. Hamilton
Engineering Sciences Center
Senior Member of Technical Staff
Sandia National Laboratories
505-844-7666
