### ISSUE TITLE
Datatables support

### ISSUE THREAD

**Issue by FrankyBoy** [Exirel/pylint-json2html#12]
Hi,

I think it makes sense to add support for datatables to this project. So far I've identified three to-dos here:

1. add thead and tbody tags to the tables ([here](https://github.com/Exirel/pylint-json2html/blob/master/pylint_json2html/templates/report.jinja2#L40))
2. include the appropriate libraries via CDN (so we don't needlessly blow up the project size) and add a simple initalization 
    ```
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css" />
    <script type="text/javascript" src="//cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>

    <script>
        $(document).ready(function(){
          $('table').DataTable();
        });
    </script>
    ```
3. play with datatables settings, because it makes them full-width per default (ugly) 

If I get around to it I can do a pull request over the weekend. Maybe I'll also throw in collapsable sections (because in the legacy project I work on, I definitely need it :D)

**Comment by Exirel** [comment]
I'm against having any dependencies to a CDN. This can go into a jinja template. I can consider the idea of having a "contrib" template directory for that, maybe.

**Comment by FrankyBoy** [comment]
I must admit I don't get the dislike of CDNs, especially considering the alternative is having a bunch of unrelated-to-the-project code in the codebase (jquery + datatables). However it might make sense to simply add a second template, keeping the current one as default and shipping a "datatables" one that can be used via the -t option.

**Comment by Exirel** [comment]
Well, I work a lot offline without a stable (if at all) connection. So yeah, not having to rely on a CDN is a big thing for me.

**Comment by FrankyBoy** [comment]
I see. Don't think datatables is our best choice then (relatively big and needs jquery on top). Though Idk if it is possible to just somehow bundle js and css files with jinja2 (so you still only have a single html file as output). Still, maybe [list.js](https://github.com/javve/list.js) would be a better option as it is both smaller and standalone, but I didn't yet get around to mess with it today. 

Either way, for now here's my current template as a gist in case someone wants to play around. Very intentionally nothing like a change request for now ;) https://gist.github.com/FrankyBoy/d66dc68b77783b1765cb16e456862c79

**Comment by Exirel** [comment]
I'm going to close that one, people will figure out how to do that on their own I believe. Plus there is a good gist in here!
