### ISSUE TITLE
incompatibility with pylint 3.x

### ISSUE THREAD

**Issue by cclecle** [Exirel/pylint-json2html#14]
Since pylint 3.x update, pylint-json2html import fails:
```ImportError: cannot import name 'IReporter' from 'pylint.interfaces'```

**Found in pylint-json2html version 0.4.0**

**Comment by immanuel-h** [comment]
Yep, also just ran into this. Looking at the current importers, I do not see the IReporter interface being used anywhere, so maybe just removing https://github.com/Exirel/pylint-json2html/blob/main/pylint_json2html/__init__.py#L166 and the import in L17 could already be sufficient.

**Comment by eloyAM** [comment]
Same problem. I used the patch and it's working.
Any idea of when could it be merged?

**Comment by d0b3rm4n** [comment]
> Same problem. I used the patch and it's working. Any idea of when could it be merged?

Probably a good start would be if somebody could make a Pull Request with 8fbf3275c92f59ea4f787c7332c4424d7df1cdb3 and @Exirel could then review, merge and release it to PyPi?

**Comment by Exirel** [comment]
Oh. I haven't seen that issue, sorry, I have issue receiving the appropriate github notifications... That being said, I'm AFK until November 6, so I probably won't do anything until then. Sorry for the inconvenience.

**Comment by Exirel** [comment]
And version 0.5.0 is up! Sorry for the delay.
