### ISSUE TITLE
Could we add support for custom templates?

### ISSUE THREAD

**Issue by deavid** [Exirel/pylint-json2html#3]
Hi, we're using your project to incorporate the report onto sphinx:

https://deavidsedice.gitlab.io/pineboo/linters/pylint/application.html

One of the main drawbacks is the HTML is complete and is not easily embedded into the theme. We needed to reduce text (we used some sed magic); but also it would be nice to remove or join some columns as well.

I had a look on the source code and seems you have a jinja template. Would be nice if there were many available and allow to select one of those, or even to refer to a file in our source code to use instead.

**Comment by ghost** [comment]
I created a simple tweak to add support for custom template at https://github.com/Dorian-LEFEUVRE/pylint-json2html.
I uploaded it to Pypi as pylint-json2html-v2. I don't ensure it's really good quality but it works for my case. I'll be happy to delete my version if someone has a better solution.

**Comment by Exirel** [comment]
Thanks for using this little project of mine! I did it for myself, and I'm glad to see someone using it.

> I had a look on the source code and seems you have a jinja template. Would be nice if there were many available and allow to select one of those, or even to refer to a file in our source code to use instead.

Oh, that's a nice idea indeed. I don't really have time at the moment to work on that project, it'll have to wait until September. But if anyone wants to do a Pull Request, I should have time to see what I can accept and publish.

@Dorian-LEFEUVRE thanks for your time and effort in that, would you like to publish a PR?

**Comment by deavid** [comment]
I can't work on it either; if no one can raise a PR in 1-2 months I'll give it a try, hopefully I would have more time by then.

We are trying to integrate it inside Sphinx:
https://aulla.gitlab.io/pineboo/linters/pylint/application.html

Using some bash magic we could include it. Not the best thing on the world, but it reads nicely.
If anyone is interested, here is the magic script:
https://github.com/Aulla/pineboo/blob/master/docs/update_linters.sh#L18

**Comment by Exirel** [comment]
Oh. I'm impressed, that looks nice.

Yes, I'll have time to work on that by September.

**Comment by ghost** [comment]
I'll do a PR asap, just need to take a bit of time to rework it properly

**Comment by Exirel** [comment]
This is now possible with version 0.2.0 available now on pypi:

    pylint-json2html -t my_template.jinja --input-format jsonextended --output report.html pylint.json
